-- MySQL Script generated by MySQL Workbench
-- Wed Mar 16 17:30:18 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Pizzeria
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Pizzeria
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Pizzeria` DEFAULT CHARACTER SET utf8 ;
USE `Pizzeria` ;

-- -----------------------------------------------------
-- Table `Pizzeria`.`CATEGORIA`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Pizzeria`.`CATEGORIA` ;

CREATE TABLE IF NOT EXISTS `Pizzeria`.`CATEGORIA` (
  `id_categoria` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_categoria`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Pizzeria`.`CLIENTE`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Pizzeria`.`CLIENTE` ;

CREATE TABLE IF NOT EXISTS `Pizzeria`.`CLIENTE` (
  `id_cliente` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `apellido` VARCHAR(45) NOT NULL,
  `direccion` VARCHAR(45) NOT NULL,
  `codigo_postal` VARCHAR(5) NOT NULL,
  `telefono` VARCHAR(9) NOT NULL,
  `LOCALIDAD_id_localidad` INT NOT NULL,
  PRIMARY KEY (`id_cliente`),
  INDEX `fk_CLIENTE_LOCALIDAD1_idx` (`LOCALIDAD_id_localidad` ASC) VISIBLE,
  CONSTRAINT `fk_CLIENTE_LOCALIDAD1`
    FOREIGN KEY (`LOCALIDAD_id_localidad`)
    REFERENCES `Pizzeria`.`LOCALIDAD` (`id_localidad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Pizzeria`.`CONTIENE`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Pizzeria`.`CONTIENE` ;

CREATE TABLE IF NOT EXISTS `Pizzeria`.`CONTIENE` (
  `PEDIDO_id_pedido` INT NOT NULL,
  `PRODUCTO_id_producto` INT NOT NULL,
  `cantidad` INT NOT NULL,
  PRIMARY KEY (`PEDIDO_id_pedido`, `PRODUCTO_id_producto`),
  INDEX `fk_PEDIDO_has_PRODUCTO_PRODUCTO1_idx` (`PRODUCTO_id_producto` ASC) VISIBLE,
  INDEX `fk_PEDIDO_has_PRODUCTO_PEDIDO1_idx` (`PEDIDO_id_pedido` ASC) VISIBLE,
  CONSTRAINT `fk_PEDIDO_has_PRODUCTO_PEDIDO1`
    FOREIGN KEY (`PEDIDO_id_pedido`)
    REFERENCES `Pizzeria`.`PEDIDO` (`id_pedido`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PEDIDO_has_PRODUCTO_PRODUCTO1`
    FOREIGN KEY (`PRODUCTO_id_producto`)
    REFERENCES `Pizzeria`.`PRODUCTO` (`id_producto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Pizzeria`.`EMPLEADO`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Pizzeria`.`EMPLEADO` ;

CREATE TABLE IF NOT EXISTS `Pizzeria`.`EMPLEADO` (
  `id_empleado` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `apellidos` VARCHAR(45) NOT NULL,
  `nif` VARCHAR(45) NOT NULL,
  `telefono` VARCHAR(9) NOT NULL,
  `profesion` ENUM("cocinero", "repartidor") NOT NULL,
  `TIENDA_id_tienda` INT NOT NULL,
  PRIMARY KEY (`id_empleado`),
  INDEX `fk_EMPLEADO_TIENDA1_idx` (`TIENDA_id_tienda` ASC) VISIBLE,
  CONSTRAINT `fk_EMPLEADO_TIENDA1`
    FOREIGN KEY (`TIENDA_id_tienda`)
    REFERENCES `Pizzeria`.`TIENDA` (`id_tienda`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Pizzeria`.`LOCALIDAD`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Pizzeria`.`LOCALIDAD` ;

CREATE TABLE IF NOT EXISTS `Pizzeria`.`LOCALIDAD` (
  `id_localidad` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `PROVINCIA_id_provincia` INT NOT NULL,
  PRIMARY KEY (`id_localidad`),
  INDEX `fk_LOCALIDAD_PROVINCIA_idx` (`PROVINCIA_id_provincia` ASC) VISIBLE,
  CONSTRAINT `fk_LOCALIDAD_PROVINCIA`
    FOREIGN KEY (`PROVINCIA_id_provincia`)
    REFERENCES `Pizzeria`.`PROVINCIA` (`id_provincia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Pizzeria`.`PEDIDO`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Pizzeria`.`PEDIDO` ;

CREATE TABLE IF NOT EXISTS `Pizzeria`.`PEDIDO` (
  `id_pedido` INT NOT NULL AUTO_INCREMENT,
  `fecha_pedido` DATETIME NOT NULL,
  `tipo_entrega` ENUM("domicilio", "tienda") NOT NULL,
  `total` FLOAT NOT NULL,
  `CLIENTE_id_cliente` INT NOT NULL,
  `TIENDA_id_tienda` INT NOT NULL,
  `fecha_entrega_pedido` DATETIME NULL,
  `EMPLEADO_id_empleado_Repartidor` INT NULL,
  PRIMARY KEY (`id_pedido`),
  INDEX `fk_PEDIDO_CLIENTE1_idx` (`CLIENTE_id_cliente` ASC) VISIBLE,
  INDEX `fk_PEDIDO_TIENDA1_idx` (`TIENDA_id_tienda` ASC) VISIBLE,
  INDEX `fk_PEDIDO_EMPLEADO1_idx` (`EMPLEADO_id_empleado_Repartidor` ASC) VISIBLE,
  CONSTRAINT `fk_PEDIDO_CLIENTE1`
    FOREIGN KEY (`CLIENTE_id_cliente`)
    REFERENCES `Pizzeria`.`CLIENTE` (`id_cliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PEDIDO_TIENDA1`
    FOREIGN KEY (`TIENDA_id_tienda`)
    REFERENCES `Pizzeria`.`TIENDA` (`id_tienda`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PEDIDO_EMPLEADO1`
    FOREIGN KEY (`EMPLEADO_id_empleado_Repartidor`)
    REFERENCES `Pizzeria`.`EMPLEADO` (`id_empleado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Pizzeria`.`PIZZA`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Pizzeria`.`PIZZA` ;

CREATE TABLE IF NOT EXISTS `Pizzeria`.`PIZZA` (
  `CATEGORIA_id_categoria` INT NOT NULL,
  `PRODUCTO_id_producto` INT NOT NULL,
  PRIMARY KEY (`CATEGORIA_id_categoria`),
  INDEX `fk_PIZZA_PRODUCTO1_idx` (`PRODUCTO_id_producto` ASC) VISIBLE,
  CONSTRAINT `fk_PIZZA_CATEGORIA1`
    FOREIGN KEY (`CATEGORIA_id_categoria`)
    REFERENCES `Pizzeria`.`CATEGORIA` (`id_categoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PIZZA_PRODUCTO1`
    FOREIGN KEY (`PRODUCTO_id_producto`)
    REFERENCES `Pizzeria`.`PRODUCTO` (`id_producto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Pizzeria`.`PRODUCTO`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Pizzeria`.`PRODUCTO` ;

CREATE TABLE IF NOT EXISTS `Pizzeria`.`PRODUCTO` (
  `id_producto` INT NOT NULL AUTO_INCREMENT,
  `nombre` ENUM("Pizza", "Hamburguesa", "Bebida") NOT NULL,
  `descripcion` VARCHAR(45) NOT NULL,
  `imagen` VARCHAR(45) NOT NULL,
  `precio` FLOAT NOT NULL,
  PRIMARY KEY (`id_producto`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Pizzeria`.`PROVINCIA`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Pizzeria`.`PROVINCIA` ;

CREATE TABLE IF NOT EXISTS `Pizzeria`.`PROVINCIA` (
  `id_provincia` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_provincia`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Pizzeria`.`TIENDA`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Pizzeria`.`TIENDA` ;

CREATE TABLE IF NOT EXISTS `Pizzeria`.`TIENDA` (
  `id_tienda` INT NOT NULL AUTO_INCREMENT,
  `direccion` VARCHAR(45) NOT NULL,
  `codigo_postal` VARCHAR(5) NOT NULL,
  `LOCALIDAD_id_localidad` INT NOT NULL,
  PRIMARY KEY (`id_tienda`),
  INDEX `fk_TIENDA_LOCALIDAD1_idx` (`LOCALIDAD_id_localidad` ASC) VISIBLE,
  CONSTRAINT `fk_TIENDA_LOCALIDAD1`
    FOREIGN KEY (`LOCALIDAD_id_localidad`)
    REFERENCES `Pizzeria`.`LOCALIDAD` (`id_localidad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
